[package]
name = "brrr"
version = "0.2.0"
edition = "2024"

[dependencies]
brrr-core = { path = "../brrr-core" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
tokio = { version = "1", features = ["full"] }
libc = "0.2"
regex = "1"
serde_json = "1"
upon = "0.10"
ureq = { version = "3", features = ["json"] }
dirs = "6.0.0"
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
serial_test = "3"
assert_cmd = "2"
predicates = "3"
serde_json = "1"
